<a href="https://colab.research.google.com/github/isabelastolf/isabelastolf/blob/main/Analise_PNAD_2015.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
#uploading database
data = pd.read_csv('dados.csv')

In [ ]:
#sampling to visualize some data
data.sample(30)

       UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
68973  50     1     67    2              12   1100  1.679216
56285  41     1     44    2              12   1030  1.700362
36768  31     0     38    8               5    900  1.541300
38949  31     0     60    8               1      0  1.921566
73435  52     1     35    8              16   2500  1.624612
58105  41     0     39    2               9   1000  1.473934
51663  35     0     69    2               1   1200  1.601545
7412   15     0     60    8               4   3000  1.636505
68467  50     0     28    4              12   1600  1.900229
61836  43     1     46    2              10   1700  1.857158
49264  35     0     46    2              12   2400  1.781463
48230  35     1     57    2              11   2000  1.815209
73467  52     0     40    4               6   1200  1.692541
71900  52     0     41    8              12  10000  1.633724
19338  25     0     49    8               5    800  1.701031
12194  21     1     43    2              12   5000  1.548383
66889  43     0     51    2               6   2400  1.714394
16525  23     0     25    8              10    788  1.683236
48599  35     0     38    4              12   2000  1.653375
22507  26     1     55    8              16   1900  1.536397
65473  43     1     52    2              12   2300  1.801447
57785  41     1     54    2              12   5000  1.786651
40877  32     0     63    8               6   3000  1.639801
25538  28     0     34    8              11   4030  1.840326
61627  42     1     26    2              12   2000  1.761795
62280  43     0     50    2               8   1800  1.819646
27486  29     0     64    8               9   2000  1.649500
59329  41     0     74    8               1      0  1.692829
17053  23     0     37    8              12   1800  1.808701
50850  35     0     57    2               7  12000  1.704634

# Starting the analysis

# Checking Gender, Color and State
<p> Gender (Sexo), Color (Cor) and State (UF)

In [ ]:
# as the database talks about the family chief information, I wanted to 
# understand better the dynamics

In [ ]:
# are there more male or female chiefs?
data['Sexo'].value_counts()

0    53250
1    23590
Name: Sexo, dtype: int64

In [ ]:
gender_frequency = data['Sexo'].value_counts()
gender_percentage = data['Sexo'].value_counts(normalize = True) * 100
freq_gender = pd.DataFrame({'Frequency': gender_frequency, 'Percentage (%)': gender_percentage})
freq_gender.rename(index = {0: 'Male', 1: 'Female'}, inplace = True)
freq_gender.rename_axis('Gender', axis = 'columns', inplace = True)

In [ ]:
freq_gender

Gender  Frequency  Percentage (%)
Male        53250       69.299844
Female      23590       30.700156

In [ ]:
# which color is more frequent between chiefs
color_frequency = data['Cor'].value_counts()
color_percentage = data['Cor'].value_counts(normalize = True) * 100
freq_color = pd.DataFrame({'Frequency': color_frequency, 'Percentage (%)': color_percentage})
freq_color.rename(index = {0: 'Indigenous', 2: 'White', 4: 'Black', 6: 'Yellow', 8: 'Brown', 9: 'Not declared'}, inplace = True)
freq_color.rename_axis('Color', axis = 'columns', inplace = True)

In [ ]:
freq_color

Color       Frequency  Percentage (%)
Brown           35925       46.752993
White           31815       41.404217
Black            8391       10.920094
Indigenous        357        0.464602
Yellow            352        0.458095

In [ ]:
# which UF has the most family chiefs
UF_frequency = data['UF'].value_counts()
UF_percentage = data['UF'].value_counts(normalize = True) * 100
freq_UF = pd.DataFrame({'Frequency': UF_frequency, 'Percentage (%)': UF_percentage})
freq_UF.rename(index = {11:	'Rondônia', 12:	'Acre', 13:	'Amazonas', 14:	'Roraima', 15:	'Pará', 16:	'Amapá', 17:	'Tocantins', 
                        21:	'Maranhão', 22:	'Piauí', 23:	'Ceará', 24:	'Rio Grande do Norte', 25:	'Paraíba', 26:	'Pernambuco', 27:	'Alagoas', 28:	'Sergipe', 29:	'Bahia',
                        31:	'Minas Gerais', 32:	'Espírito Santo', 33:	'Rio de Janeiro', 35:	'São Paulo', 
                        41:	'Paraná', 42:	'Santa Catarina', 43:	'Rio Grande do Sul', 
                        50:	'Mato Grosso do Sul', 51:	'Mato Grosso', 52:	'Goiás', 53:	'Distrito Federal'}, inplace = True)
freq_UF.rename_axis('UF', axis = 'columns', inplace = True)

In [ ]:
freq_UF

UF                   Frequency  Percentage (%)
São Paulo                 8544       11.119209
Minas Gerais              7686       10.002603
Rio Grande do Sul         6322        8.227486
Bahia                     5717        7.440135
Rio de Janeiro            5556        7.230609
Pará                      4449        5.789953
Paraná                    4356        5.668922
Pernambuco                3820        4.971369
Goiás                     3478        4.526288
Ceará                     3359        4.371421
Santa Catarina            2275        2.960698
Amazonas                  2206        2.870901
Distrito Federal          2054        2.673087
Mato Grosso               1800        2.342530
Maranhão                  1787        2.325612
Rondônia                  1537        2.000260
Espírito Santo            1511        1.966424
Mato Grosso do Sul        1440        1.874024
Tocantins                 1306        1.699636
Sergipe                   1287        1.674909
Paraíba                   1274        1.657991
Piauí                     1211        1.576002
Rio Grande do Norte        973        1.266268
Acre                       937        1.219417
Alagoas                    903        1.175169
Roraima                    540        0.702759
Amapá                      512        0.666320

# Checking the Income (Renda)

In [ ]:
data.Renda.min()

In [ ]:
data.Renda.max()

In [ ]:
classes = [0, 1576, 3152, 7880, 15760, 200000]

In [ ]:
labels = ['E', 'D', 'C', 'B', 'A']

In [ ]:
pd.cut(x = data.Renda,
       bins = classes,
       labels = labels,
       include_lowest = True)

In [ ]:
frequency_income = pd.value_counts(
    pd.cut(x = data.Renda,
       bins = classes,
       labels = labels,
       include_lowest = True)
)
frequency_income

In [ ]:
percentage_income = pd.value_counts(
    pd.cut(x = data.Renda,
       bins = classes,
       labels = labels,
       include_lowest = True),
       normalize = True
) * 100
percentage_income = percentage_income.round()
percentage_income

In [ ]:
freq_income = pd.DataFrame({'Frequency': frequency_income, 'Percentage (%)': percentage_income})
freq_income
freq_income.sort_index(ascending = False)